--------------------------------------------------------
--  File created - Friday-May-02-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_NEMUMENU
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."USER_NEMUMENU" 
   (	"USER_ID" VARCHAR2(6 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD_USER" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESTORAN
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."RESTORAN" 
   (	"RESTO_ID" VARCHAR2(6 BYTE), 
	"NAMA_RESTO" VARCHAR2(50 BYTE), 
	"IMAGE" BLOB, 
	"LOKASI" VARCHAR2(250 BYTE), 
	"NO_TELP" VARCHAR2(16 BYTE), 
	"RANGE_HARGA" VARCHAR2(100 BYTE), 
	"WAKTU_BUKA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FAVORIT
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."FAVORIT" 
   (	"FAVORIT_ID" VARCHAR2(6 BYTE), 
	"USER_ID" VARCHAR2(6 BYTE), 
	"RESTO_ID" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."MENU" 
   (	"MENU_ID" VARCHAR2(6 BYTE), 
	"RESTO_ID" VARCHAR2(6 BYTE), 
	"IMG_MENU_1" BLOB, 
	"IMG_MENU_2" BLOB, 
	"IMG_MENU_3" BLOB, 
	"IMG_MENU_4" BLOB, 
	"IMG_MENU_5" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMG_MENU_1") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_2") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_3") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_4") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMG_MENU_5") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ULASAN
--------------------------------------------------------

  CREATE TABLE "NEMU_MENU_USER"."ULASAN" 
   (	"ULASAN_ID" VARCHAR2(6 BYTE), 
	"USER_ID" VARCHAR2(6 BYTE), 
	"RESTO_ID" VARCHAR2(6 BYTE), 
	"ULASAN_TEXT" CLOB, 
	"RATING" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ULASAN_TEXT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
REM INSERTING into NEMU_MENU_USER.USER_NEMUMENU
SET DEFINE OFF;
Insert into NEMU_MENU_USER.USER_NEMUMENU (USER_ID,USERNAME,EMAIL,PASSWORD_USER) values ('AD001','admin','admin@gmail.com','kelompok_1');
Insert into NEMU_MENU_USER.USER_NEMUMENU (USER_ID,USERNAME,EMAIL,PASSWORD_USER) values ('US001','Andhinee','andhinee@gmail.com','anak_gondang');
REM INSERTING into NEMU_MENU_USER.RESTORAN
SET DEFINE OFF;
Insert into NEMU_MENU_USER.RESTORAN (RESTO_ID,NAMA_RESTO,LOKASI,NO_TELP,RANGE_HARGA,WAKTU_BUKA) values ('RS001','Nabila Steak','Jl. Gondang Timur II','08191995999','Rp 10.000 - Rp 25.000','Senin-Jumat (12.00-20.00)');
REM INSERTING into NEMU_MENU_USER.FAVORIT
SET DEFINE OFF;
REM INSERTING into NEMU_MENU_USER.MENU
SET DEFINE OFF;
Insert into NEMU_MENU_USER.MENU (MENU_ID,RESTO_ID) values ('MN001','RS001');
REM INSERTING into NEMU_MENU_USER.ULASAN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."USER_ID" ON "NEMU_MENU_USER"."USER_NEMUMENU" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESTO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."RESTO_ID" ON "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FAVORIT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."FAVORIT_ID" ON "NEMU_MENU_USER"."FAVORIT" ("FAVORIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."MENU_ID" ON "NEMU_MENU_USER"."MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ULASAN_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEMU_MENU_USER"."ULASAN_ID" ON "NEMU_MENU_USER"."ULASAN" ("ULASAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_NEMUMENU
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."USER_NEMUMENU" ADD CONSTRAINT "USER_ID" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTORAN
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."RESTORAN" ADD CONSTRAINT "RESTO_ID" PRIMARY KEY ("RESTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAVORIT
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."FAVORIT" ADD CONSTRAINT "FAVORIT_ID" PRIMARY KEY ("FAVORIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."MENU" ADD CONSTRAINT "MENU_ID" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ULASAN
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CHECK (rating BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CONSTRAINT "ULASAN_ID" PRIMARY KEY ("ULASAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAVORIT
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."FAVORIT" ADD CONSTRAINT "USER_ID_FAV" FOREIGN KEY ("USER_ID")
	  REFERENCES "NEMU_MENU_USER"."USER_NEMUMENU" ("USER_ID") ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."FAVORIT" ADD CONSTRAINT "RESTO_ID_FAV" FOREIGN KEY ("RESTO_ID")
	  REFERENCES "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."MENU" ADD CONSTRAINT "RESTO_ID_MENU" FOREIGN KEY ("RESTO_ID")
	  REFERENCES "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ULASAN
--------------------------------------------------------

  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CONSTRAINT "USER_ID_UL" FOREIGN KEY ("USER_ID")
	  REFERENCES "NEMU_MENU_USER"."USER_NEMUMENU" ("USER_ID") ENABLE;
  ALTER TABLE "NEMU_MENU_USER"."ULASAN" ADD CONSTRAINT "RESTO_ID_UL" FOREIGN KEY ("RESTO_ID")
	  REFERENCES "NEMU_MENU_USER"."RESTORAN" ("RESTO_ID") ENABLE;
